Feature/home page
PGS-dev/framapp-angular-1.5 pull request #4
Opened 2016-09-20 13:59 UTC by wuha94

2016-09-20 14:07 UTC, mtrzesniowski commented on app/components/category/category.service.js
> +        return this.$http.get(this.appConfig + 'categories' + '.json')
Please create link with more ES6 syntax - https://developer.mozilla.org/pl/docs/Web/JavaScript/Referencje/template_strings

2016-09-20 14:07 UTC, mtrzesniowski commented on app/components/category/category.service.js
> +    })
something went wrong with formatting

2016-09-20 14:09 UTC, mtrzesniowski commented on app/components/category/category.service.js
> +    .catch((response) => {
Maybe create a function in service that you can put in catch block and control request failure in every of them?

2016-09-20 14:10 UTC, mtrzesniowski commented on app/index.js
> +    .constant("appConfig", "https://woven-patrol-127817.firebaseio.com/api/v1/")
`appConfig` is not clear - maybe better something like `BASE_URL`? Also I think that constants naming should be UPPERCASE, what do you think ?

2016-09-20 14:18 UTC, mtrzesniowski commented on app/pages/main/main-page.component.js
> +            this.sortArray(this.data, this.newData);
It would be better to move logic into the service, so maybe create a function called `getPromotedProducts()` or something similar and call it

2016-09-20 14:19 UTC, mtrzesniowski requested changes

2016-09-20 14:27 UTC, wuha94 commented on app/index.js
> +    .constant("appConfig", "https://woven-patrol-127817.firebaseio.com/api/v1/")
"BASE_URL" sounds good, i can use this with uppercase.

2016-09-22 08:04 UTC, mtrzesniowski commented on app/components/app/index.js
> +    .service('appService', AppService)
Not sure if `appService` is good name - it doesn't tell us anything what that service will do

2016-09-22 08:04 UTC, mtrzesniowski commented on app/components/app/app.service.js
> +            console.log(response.statusText);
How about catching request in one function and calling it here?

2016-09-22 08:06 UTC, mtrzesniowski commented on app/pages/category/category.component.js
> +        angular.forEach(data, function (param) {
I would put as many logic in the services as I can - controller shouldn't have it too much

2016-09-22 08:07 UTC, mtrzesniowski commented on app/pages/main/main-page.component.js
> +        angular.forEach(data, function (param) {
Same stuff with putting logic into service - try to avoid it in controllers

2016-09-22 08:07 UTC, mtrzesniowski requested changes

2016-09-22 08:10 UTC, mtrzesniowski commented on app/components/app/app.service.js
> +        return this.$http.get(`${this.BASE_URL}products.json`).then((response) => {
One more thing - delete the final slash in BASE_URL, so links here will look much better with slash before `products.json`

2016-09-22 08:10 UTC, mtrzesniowski requested changes

2016-09-23 09:55 UTC, mtrzesniowski commented on app/components/app/app.service.js
> +            .catch((response) => {
no need to create arrow function - call `responseError` directly

2016-09-23 09:55 UTC, mtrzesniowski commented on app/components/app/app.service.js
> +            .catch((response) => {
no need to create arrow function - call `responseError` directly

2016-09-23 09:55 UTC, mtrzesniowski commented on app/components/category/category.component.js
> +        this.getDataService.getCategories().then((data) => {
Put `then` in a new line

2016-09-23 09:56 UTC, mtrzesniowski commented on app/pages/category/category.component.js
> +        this.getDataService.getProducts().then((data) => {
Put `then` in a new line

2016-09-23 09:56 UTC, mtrzesniowski commented on app/pages/category/category.service.js
> +    filterProductsByCategory(array) {
Add whitespace above

2016-09-23 09:56 UTC, mtrzesniowski commented on app/pages/category/category.service.js
> +        this.categoryData = array.filter(n => n.category === this.$state.params.id);
Maybe you can return new array here directly?

2016-09-23 09:57 UTC, mtrzesniowski commented on app/pages/main/main-page.component.js
> +    $onInit() {
Add whitespace above in every function (everywhere)

2016-09-23 09:57 UTC, mtrzesniowski commented on app/pages/main/main-page.component.js
> +        this.getDataService.getProducts().then(data => {
Put `then` in new line

2016-09-23 09:59 UTC, mtrzesniowski commented on app/pages/main/main-page.service.js
> +        this.promotedData = array.filter(n => n.promoted === true);
Maybe you can return new array here directly?

2016-09-23 10:01 UTC, mtrzesniowski commented on app/style/sass/common.scss
> +@media (min-width: 959px) {
I would create:
1) variables that will define breakpoints in application (like `$tablet-min`, `$tablet-max`, `$desktop-min` etc
2) mixin that will take a device parameter and use breakpoint variables to create styles, like for example:
```scss
.pgs-mainContent {
    @include breakpoint(desktop) {
        margin-left: 320px;
    }
}
```

2016-09-23 10:02 UTC, mtrzesniowski requested changes

2016-09-23 13:19 UTC, mtrzesniowski commented on app/components/app/index.js
> +    .service('getDataService', GetDataService)
I would change `getDataService` to `dataService`

2016-09-23 13:20 UTC, mtrzesniowski commented on app/pages/category/category.service.js
> +
Whitespace to delete

2016-09-23 13:20 UTC, mtrzesniowski commented on app/pages/main/main-page.service.js
> +    filterProductsByPromoted(array) {
Add whitespace above

2016-09-23 13:21 UTC, mtrzesniowski commented on app/pages/main/index.js
> +    .service('mainService', MainService)
Not sure about naming `mainService` - do you have any other, better ideas?

2016-09-23 13:21 UTC, mtrzesniowski requested changes

2016-09-23 13:43 UTC, wuha94 commented on app/pages/main/index.js
> +    .service('mainService', MainService)
Maybe `homePageService` or `homeService`

2016-09-23 13:54 UTC, mtrzesniowski commented on app/pages/main/index.js
> +    .service('mainService', MainService)
👍

2016-09-23 14:29 UTC, merged